# conf/model/dense.yaml

_target_: src.model.dense.DenseModel
name: dense

units: [256, 128, 128, 256]
dropout_rate: 0.1

# Input sizes
sequence_length: ${dataset.sequence_length}
num_features: ${dataset.num_electrodes}

# Output size
output_size: ${dataset.activation_map_size}

tb_output_dir: "${output_dir}/${model.name}_${dataset.name}/opt_${optimizer.name}_lr_${optimizer.learning_rate}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${random_number}"
