# conf/callbacks/checkpoint.yaml
checkpoint:
  _target_: tensorflow.keras.callbacks.ModelCheckpoint
  filepath: "${model.tb_output_dir}/checkpoint"
  save_weights_only: True
  monitor: 'val_loss'
  mode: 'min'
  save_best_only: True
  verbose: 1